# Generated by Django 5.0.4 on 2024-04-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Flag to implement logical deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of object created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date and time of object updated')),
                ('contact_name', models.CharField(db_index=True, max_length=50)),
                ('contact_last_name', models.CharField(db_index=True, max_length=50)),
                ('contact_phone_number', models.CharField(max_length=10)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'agenda',
                'verbose_name_plural': 'agendas',
            },
        ),
    ]
